# Generated by Django 4.2.3 on 2023-07-11 06:13

import django.core.validators
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='PossibleBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=10)),
                ('position', models.CharField(choices=[('Personal', 'Personal'), ('Business', 'Business')], max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='비밀번호는 영문 소문자와 숫자를 조합하여 7글자 이내로 입력해주세요.', regex='^[a-z0-9]+$')])),
                ('description', models.TextField(max_length=200)),
                ('file', models.FileField(blank=True, upload_to='possible/')),
                ('keywords', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='keywords')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
