# Generated by Django 4.2.3 on 2023-07-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possibleboard',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
