# Generated by Django 4.2.3 on 2023-07-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possibleboard',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
